### ISSUE TITLE
npm start fonctionne pas

### ISSUE THREAD

**Issue by ThomasAy** [PoissonPilote/website#11]
@MartinDelille : c'est ma config qui déconne ou c'est un peu plus général?

```
90% 2016-08-11 14:04:51 ☆  MBP-Thomas in ~/Dev/website
± |master ✓| → npm start

> poisson-pilote@0.0.0 start /Users/thomas/Dev/website
> node ./bin/www


/Users/thomas/Dev/website/routes/index.js:19
const getFiles = (lang) => Promise.fromNode(cb => fs.readdir('./src/' + lang, 
                         ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/thomas/Dev/website/app.js:9:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

npm ERR! poisson-pilote@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the poisson-pilote@0.0.0 start script.
npm ERR! This is most likely a problem with the poisson-pilote package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls poisson-pilote
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 15.6.0
npm ERR! command "node" "/usr/local/bin/npm" "start"
npm ERR! cwd /Users/thomas/Dev/website
npm ERR! node -v v0.10.31
npm ERR! npm -v 1.4.26
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/thomas/Dev/website/npm-debug.log
npm ERR! not ok code 0

```

**Comment by divarvel** [comment]
Tu utilises une version de node qui n'est pas à jour (tu as du avoir un warning quand tu as fait le npm install).
Il te faut la stable actuelle (6.x).

**Comment by ThomasAy** [comment]
Ah oui effectivement... Ça fonctione, merci @divarvel :)
